plugins {
    id "com.android.application"
}

android {
    namespace "com.codar.harvesthaven"
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.codar.harvesthaven"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"

        buildConfigField "String", "HARVEST_HAVEN_URL", "\"https://harvest-haven-rust.vercel.app/\""
    }
}
